### ISSUE TITLE
ELECTRA-TINY配置问题

### ISSUE THREAD

**Issue by wow-kong** [CLUEbenchmark/ELECTRA#5]
1. 您在Readme中提及的是配置和albert-tiny相同，但我看了下config.json文件，好像有些出入：
**albert:**
num_hidden_layers=4
num_attention_heads=12
hidden_size=312
embedding_size=128
intermediate_size=1248
**electra:**
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 312, 
  "initializer_range": 0.02, 
  "intermediate_size": 1200, 
  "max_position_embeddings": 512, 
  "num_attention_heads": 12, 
  "num_hidden_layers": 4, 
  "pooler_fc_size": 312, 
  "pooler_num_attention_heads": 12, 
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "type_vocab_size": 2,
  "vocab_size": 21128
并且存在部分ELECTRA代码中没有的参数，比如 "pooler_type": "first_token_transform"等

2. 另外，请问下：
`According to official results, the results may have large variance`
是什么意思呢？是指下游任务fine-tune时，多次产生的结果可能有较大差异吗？

**Comment by yyht** [comment]
1. electra-tiny的参数 和 tiny-bert（华为诺亚方舟实验室的 小模型）参数相同；
 "pooler_type": "first_token_transform" 等是 google-bert-base 里面的参数（没有实际作用）；
2. 小模型 更容易受参数初始化的影响，一般 跑10-epoch 取dev上的最好结果 会 相对好一些

**Comment by wow-kong** [comment]
1. 非常抱歉...最近用albert看走眼了..
    那么我直接用modeling中from_json_file加载配置文件，其他部分使用ELECTRA自带文件就可以了吧？
2. 很感谢，之前做fine-tuning的时候确实发现下游任务性能偏差很大，刚经您提示找到了一篇讲解初始化权重/数据顺序对pretrained model做fine-tuning影响的论文，准备研究一下

**Comment by yyht** [comment]
albert 使用的时候 参考 苏剑林的文章，把 参数 作为 各个层的初始化，然后 解除 layer之间的参数共享 会好一些（同等规模下，albert 效果 基本 都 比较差）；
跑10-epoch 基本 variance 会小一些 以及 segment-ids设置为0（electra、roberta 都是 single-sentence，使用 0，1的segment ids 会 出现一些问题，都设置为0 结果会稳定一些）

**Comment by wow-kong** [comment]
剑林那篇文章我也看到了，说是尤其在小模型下取消共享会有提升，不过还没尝试，现在也是在找albert的替代方案（如您所说同等规模下，albert 效果 基本 都 比较差，而且因为embedding_matrix分解的问题inference速度相比同等规格模型也更慢）

segment-ids都已经设置成0了，epoch个数设置学习到了，之前albert的时候基本都是5-10，electra因为需要学习的参数量比较多所以一开始设的高了些，我再降一下试试

非常感谢！
